# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe934a73b4c7648039f977d02df06b4706e3d1189c782024c79c69b003cc972f0f8097137401d58b084c0ee07d0cdb0853eef6f96cd85ec759a28346253ff7db

test:
  secret_key_base: c6cf247279f4ff0996f3a4e92cc5a9c2dd246bbd077bac58f69f5230074f5ce4847907a433c2cd816fe61bf12da02de691a143ce330e32156e688d9ed4db4d72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
